//An interface of an PlanOrder booked by the user
export class AdminOrderDetails
{
    Name:string;
    first:string;
    second:string;
    email:string;
    Phone:string;
    selectday1:string;
    selectday2:string;
    selectday3:string;
    Time1:string;
    Time2:String;
    Time3:string;
    startDate:string;
    endDate:string;
    PlanName:string;
    Price:string;
    Validity:string;
    Vehicle:string;
    planId:string;
    RegNum:string;
    Type:string;
    Saving:string;
    WashDays:string;
    Address:string;
    order_id:string;
    razorpay_payment_id:string;
    BookingDate:string;
    Mode:string;
    Pincode:string;
}